import { ToastContainer } from "react-toastify";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create New Class",
  description: "Generated by our app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-green-400 to-blue-400">
        <Navbar />
      
        <div className="main-container max-w-7xl mx-auto  ">{children}</div>
      </body>
    </html>
  );
}
