import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create New Class",
  description: "Generated by our app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main-container max-w-7xl mx-auto ">{children}</div>
      </body>
    </html>
  );
}
