"use client";
// import axios from "axios";
import Link from "next/link";

import React, { useState } from "react";
export const metadata = {
  title: "Register-S.A.M",
  description: "Generated by our app",
};

const Register = () => {
  return (
    <div className="max-w-7xl h-[80vh] md:h-[100vh] flex justify-center items-center ">
      <form
        className=" w-[90vw] md:w-[30%] p-2 h-max flex flex-col gap-4 "
        // onSubmit={handleSubmit}
      >
        <input
          type="text"
          placeholder="Full Name"
          required
          name="name"
          className="h-16 rounded-lg border-2 border-green-500 p-2 font-bold text-lg bg-black text-white "
        />
        <input
          type="text"
          placeholder="E-mail"
          required
          name="email"
          className="h-16 rounded-lg border-2 border-green-500 p-2 font-bold text-lg bg-black text-white "
        />
        <input
          type="password"
          placeholder="password"
          required
          name="password"
          className="h-16 rounded-lg border-2 border-green-500 p-2 font-bold text-lg bg-black text-white "
        />
        <input
          type="text"
          placeholder="class Division In capital"
          required
          name="Divsion"
          className="h-16 rounded-lg border-2 border-green-500 p-2 font-bold text-lg bg-black text-white "
        />
        <input
          type="number"
          placeholder="Roll no"
          required
          name="rollno"
          className="h-16 rounded-lg border-2 border-green-500 p-2 font-bold text-lg bg-black text-white "
        />
        <button
          type="submit"
          className="text-white border-2 border-green-500 bg-green-500 rounded-lg h-16 "
        >
          Register
        </button>
        {/* {err && (
          <p className="text-center text-red-700 ">
            Try again something went wrong
          </p>
        )} */}
        <Link
          href="/dashboard/login"
          className="text-blue-500 underline text-center hover:text-red-500 "
        >
          Login with an existing account
        </Link>
      </form>
    </div>
  );
};

export default Register;
